version: '3.8'

services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    ports:
      - "8081:8081"
    volumes:
      - ./cookies:/cookies
    environment:
      - YTDL_OPTIONS={"cookiefile":"/cookies/cookies.txt","format":"bestaudio[ext=webm]/bestaudio"}
    restart: unless-stopped
